//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLDIL()
        {
            this.TBLKITAP = new HashSet<TBLKITAP>();
        }
    
        public int DILID { get; set; }
        public string DILAD { get; set; }
        public Nullable<int> EKLEYEN { get; set; }
    
        public virtual TBLKULLANICILAR TBLKULLANICILAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKITAP> TBLKITAP { get; set; }
    }
}
