//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEMANET
    {
        public int EMANETID { get; set; }
        public Nullable<int> UYENO { get; set; }
        public Nullable<int> KITAPNO { get; set; }
        public Nullable<System.DateTime> VERILMETTARIHI { get; set; }
        public Nullable<System.DateTime> IADETARIHI { get; set; }
        public Nullable<System.DateTime> ISLEMTARIH { get; set; }
        public string EMANETNO { get; set; }
        public Nullable<bool> TESLIMEDILDI { get; set; }
        public Nullable<int> EKLEYEN { get; set; }
    
        public virtual TBLKITAP TBLKITAP { get; set; }
        public virtual TBLKULLANICILAR TBLKULLANICILAR { get; set; }
        public virtual TBLUYE TBLUYE { get; set; }
    }
}
