//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANICILAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKULLANICILAR()
        {
            this.TBLDIL = new HashSet<TBLDIL>();
            this.TBLEMANET = new HashSet<TBLEMANET>();
            this.TBLKITAP = new HashSet<TBLKITAP>();
            this.TBLUYE = new HashSet<TBLUYE>();
        }
    
        public int ID { get; set; }
        public string KADI { get; set; }
        public string KSIFRE { get; set; }
        public string ADSOYAD { get; set; }
        public string GOREV { get; set; }
        public Nullable<int> YETKI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDIL> TBLDIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEMANET> TBLEMANET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKITAP> TBLKITAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUYE> TBLUYE { get; set; }
    }
}
