//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKITAP()
        {
            this.TBLEMANET = new HashSet<TBLEMANET>();
        }
    
        public int KITAPID { get; set; }
        public string KITAPAD { get; set; }
        public string KITAPYAZARI { get; set; }
        public Nullable<int> KITAPBASIMYIL { get; set; }
        public Nullable<int> KITAPSAYFASAYI { get; set; }
        public Nullable<int> KITAPDIL { get; set; }
        public string KITAPYAYINEVI { get; set; }
        public string KITAPACIKLAMA { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<int> EKLEYEN { get; set; }
        public string BARKOD { get; set; }
        public string KITAPTURU { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
    
        public virtual TBLDIL TBLDIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEMANET> TBLEMANET { get; set; }
        public virtual TBLKULLANICILAR TBLKULLANICILAR { get; set; }
    }
}
