//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUYE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUYE()
        {
            this.TBLEMANET = new HashSet<TBLEMANET>();
        }
    
        public int UYEID { get; set; }
        public string UYEADSOYAD { get; set; }
        public string UYETEL { get; set; }
        public string UYEEPOSTA { get; set; }
        public string UYEADRES { get; set; }
        public Nullable<int> EKLEYEN { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEMANET> TBLEMANET { get; set; }
        public virtual TBLKULLANICILAR TBLKULLANICILAR { get; set; }
    }
}
